### ISSUE TITLE
Problems while running the code

### ISSUE THREAD

**Issue by GilbertHeywood** [TUM-LMF/BreizhCrops#2]
Could you elaborate on how to run your codes? Some modules like AttentionModule is missing and we don't know which should be the correct input. The current input is from tslearn dataset named "Trace". I believe it is not the correct input, right?

**Comment by MarcCoru** [comment]
Hi @GilbertHeywood, 

apologies for the unclear description of the data. This repository or originally used to exclusively download and store the data. I copy-pasted the training models for completeness before the workshop paper submission but did not find any time since then to build proper documentation. Thanks to your issue I got to clean up and refactor the code. 
I also added a Jupyter Notebook `TrainEvaluateModels.ipynb`. This should give clear instructions on how to execute the code to train and evaluate the models from the paper. 

Let me know if anything is still unclear. Any feedback is highly welcome!

Cheers,
Marc
